### ISSUE TITLE
Tailwind não está funcionando corretamente

### ISSUE THREAD

**Issue by filipe-torres** [thiagoferrax/super-tags#1]
Segui todos os passos descritos em [https://github.com/thiagoferrax/super-tags/tree/develop](https://github.com/thiagoferrax/super-tags/tree/develop) e consegui executar a aplicação. No entanto, os estilos do Tailwind não foram aplicados às tags HTML (ver imagem abaixo):
![Captura de tela 2024-06-19 100352](https://github.com/thiagoferrax/super-tags/assets/1202645/09a644c8-266e-41f5-9e97-aec202137b10)

Ao ler o guia de instalação do Tailwind no Next.js [https://tailwindcss.com/docs/guides/nextjs](https://tailwindcss.com/docs/guides/nextjs) e analisar o arquivo **package.json**, percebi que a dependência **autoprefixer** não estava presente. Assim, instalei novamente as dependências do Tailwind com o comando `npm install -D tailwindcss postcss autoprefixer`, que atualizou as dependências **tailwindcss** e **postcss** e instalou o **autoprefixer** que estava faltando, mas o problema persistiu.

Analisei o arquivo **tailwind.config.ts** e percebi que estava diferente do que recomenda a documentação do Tailwind na página [https://tailwindcss.com/docs/configuration#using-esm-or-type-script](https://tailwindcss.com/docs/configuration#using-esm-or-type-script). Ajustei o arquivo **tailwind.config.ts** de:
```typescript
import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
    //   backgroundImage: {
    //     "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
    //     "gradient-conic":
    //       "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
    //   },
    },
  },
  plugins: [],
};
export default config;
```

para:
```typescript
import type { Config } from 'tailwindcss'

export default {
  content: ["./src/app/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {},
  },
  plugins: [],
} satisfies Config
```

Infelizmente o problema ainda persistiu.

**Comment by jmacnico** [comment]
Após ter alterado a versão do next passou a funcionar
